List<String> search = [
  "University of Cape Town",
  "University of the Witwatersrand",
  "Stellenbosch University",
  "University of Pretoria",
  "University of KwaZulu-Natal",
  "University of Johannesburg",
  "Rhodes University",
  "North-West University",
  "University of the Western Cape",
  "Nelson Mandela University",
  "University of South Africa",
  "University of the Free State",
  "Tshwane University of Technology",
  "Cape Peninsula University of Technology",
  "Durban University of Technology",
  "Central University of Technology",
  "Vaal University of Technology",
  "Walter Sisulu University",
  "University of Fort Hare",
  "University of Limpopo",
  "Mangosuthu University of Technology",
  "Sefako Makgatho University",
  "Sol Plaatje University",
  "University of Mpumalanga",
  "University of Venda",
  "University of Zululand",
  "Central Johannesburg TVET College",
  "Ekurhuleni East TVET College",
  "Ekurhuleni West TVET College",
  "Sedibeng TVET College",
  "South West Gauteng TVET College",
  "Tshwane South College",
  "Western TVET College",
  "Coastal KZN TVET College",
  "Elangeni TVET College",
  "Esayidi TVET College",
  "Majuba TVET College",
  "Mnambithi TVET College",
  "Mthashana TVET College",
  "uMfolozi TVET College",
  "Umgungundlovu TVET College",
  "Boland TVET College",
  "College of Cape Town",
  "False Bay College",
  "Northlink TVET College",
  "South Cape TVET College",
  "Mopani South East TVET College",
  "Buffalo City TVET College",
  "Eastcape Midlands TVET College",
  "Ingwe TVET College",
  "King Hintsa TVET College",
  "King Sabata Dalindyebo TVET College",
  "Lovedale TVET College",
  "Flavius Mareka TVET College",
  "Port Elizabeth TVET College",
  "Maluti TVET College",
  "Goldfields TVET College",
  "Motheo TVET College",
  "Capricorn TVET College",
  "Lephalale TVET College",
  "Letaba TVET College",
  "Thekwini TVET College",
  "Sekhukhune TVET College",
  "Vhembe TVET College",
  "Waterberg TVET College",
  "Ehlanzeni TVET College",
  "Gert Sibande TVET College",
  "Nkangala TVET College",
  "Northern Cape Urban TVET College",
  "Orbit TVET College",
  "Taletso TVET College",
  "Vuselela TVET College",
  "West Coast TVET College",
  "Ikhala TVET College",
  "Northern Cape Rural TVET College",
  "Tshwane North TVET College",
];

List<String> grades = [
  "Grade 10",
  "Grade 11",
  "Grade 12",
];
