final List<String> electives = [
  "Accounting",
  "Agricultural Management Practices",
  "Agricultural Sciences",
  "Agricultural Technology",
  "Associated Board Of Royal ...",
  "Business Studies",
  "Civil Technology",
  "Computer Applications Technology",
  "Consumer Studies",
  "Dance Studies",
  "Design",
  "Dramatic Arts",
  "Economics",
  "Electrical Technology",
  "Engineering Graphics and Design",
  "Equine Studies",
  "Geography",
  "History",
  "Hospitality Studies",
  "Information Technology",
  "Italian (Second Additional Language)",
  "Latin (Second Additional Language)",
  "Life Sciences",
  "Maritime Economics",
  "Mechanical Technology",
  "Music",
  "Nautical Science",
  "Physical Sciences",
  "Religion Studies",
  "Sport and Exercise Science",
  "Technical Mathematics",
  "Technical Sciences",
  "Tourism",
  "Trinity College of London ...",
  "UNISA Practical Music",
  "Visual Arts",
  "None",
];

final List<String> homeLanguages = [
  "Afrikaans",
  "English",
  "isiNdebele",
  "isiXhosa",
  "isiZulu",
  "Sepedi",
  "Sesotho",
  "Setswana",
  "SiSwati",
  "Tshivenda",
  "Xitsonga",
  "None"
];

final List<String> firstAdditionalLanguages = [
  "Afrikaans",
  "English",
  "isiNdebele",
  "isiXhosa",
  "isiZulu",
  "Sepedi",
  "Sesotho",
  "Setswana",
  "SiSwati",
  "Tshivenda",
  "Xitsonga",
];

final List<String> secondAdditionalLanguages = [
  "English ",
  "Afrikaans ",
  "isiNdebele ",
  "isiXhosa ",
  "isiZulu ",
  "Sepedi (Northern Sotho) ",
  "Sesotho (Southern Sotho) ",
  "Setswana (Tswana) ",
  "SiSwati (Swazi) ",
  "Tshivenda ",
  "Xitsonga ",
  "Arabic ",
  "French ",
  "German ",
  "Gujarati ",
  "Hebrew ",
  "Hindi ",
  "Italian ",
  "Latin ",
  "Mandarin ",
  "Modern Greek ",
  "None"
];

final List<String> mathematics = [
  "Mathematics",
  "Mathematical Literacy",
  "Technical Mathematics",
];

final List<String> allSubjects = [
  "Accounting",
  "Advanced Programme Mathematics",
  "Afrikaans",
  "Agricultural Management Practices",
  "Agricultural Sciences",
  "Agricultural Technology",
  "Arabic",
  "Business Studies",
  "Civil Technology",
  "Computer Applications Technology",
  "Consumer Studies",
  "Dance Studies",
  "Design",
  "Dramatic Arts",
  "Economics",
  "South African Sign Language",
  "Electrical Technology",
  "Engineering Graphics and Design",
  "English",
  "Equine Studies",
  "French",
  "Geography",
  "German",
  "Greek",
  "Gujarati",
  "Hebrew",
  "Hindi",
  "History",
  "Hospitality Studies",
  "Information Technology",
  "Latin",
  "Life Orientation",
  "Life Sciences",
  "Mandarin",
  "Mathematical Literacy",
  "Mathematics",
  "Mechanical Technology",
  "Music",
  "Nautical Science",
  "Physical Science",
  "Religion Studies",
  "Science",
  "Sciences",
  "Sepedi",
  "Sesotho",
  "Setswana",
  "SiSwati",
  "Studies",
  "Technical",
  "Technical Mathematics",
  "Technical Sciences",
  "Telegu",
  "Tourism",
  "Tshivenda",
  "UNISA Practical Music",
  "Urdu",
  "Visual",
  "Visual Arts",
  "Visual Culture Studies",
  "Xitsonga",
  "isiNdebele",
  "isiXhosa",
  "isiZulu"
];

final List<String> uniqueSubjects = allSubjects.toSet().toList();
