List<String> universities = [
  "University of Cape Town (UCT)",
  "University of the Witwatersrand (Wits)",
  "Stellenbosch University (SU)",
  "University of Pretoria (UP)",
  "University of KwaZulu-Natal (UKZN)",
  "University of Johannesburg (UJ)",
  "Rhodes University (RU)",
  "North-West University (NWU)",
  "University of the Western Cape (UWC)",
  "Nelson Mandela University (NMU)",
  "University of South Africa (UNISA)",
  "University of the Free State (UFS)",
  "Tshwane University of Technology (TUT)",
  "Cape Peninsula University of Technology (CPUT)",
  "Durban University of Technology (DUT)",
  "Central University of Technology (CUT)",
  "Vaal University of Technology (VUT)",
  "Walter Sisulu University (WSU)",
  "University of Fort Hare (UFH)",
  "University of Limpopo (UL)",
  "Mangosuthu University of Technology (MUT)",
  "Sefako Makgatho Health Sciences University (SMU)",
  "Sol Plaatje University (SPU)",
  "University of Mpumalanga (UMP)"
];
